"""
fetch_open_data.py
====================
This script has TWO modes:

1. `--mode real`   : downloads ACTUAL open data from the sources listed in
                      docs/data_provenance.md. Run this on your own machine
                      (not in this sandbox) as it requires access to external
                      domains (ESDM, NOAA/Caltech, GFZ Potsdam,
                      Global Energy Monitor).

2. `--mode sample` : regenerates SAMPLE/PLACEHOLDER data used in
                      notebooks/00_tier1_national_screening.ipynb, ensuring
                      the notebooks can be run end-to-end without internet,
                      and allows others to inspect the structure before
                      swapping in the real data.

IMPORTANT: The data generated by "sample" mode is NOT real geological/emission
data. The values are illustrative to demonstrate the pipeline structure. 
Do not use them as a basis for any decisions. See docs/methodology.md §Limitations.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
EXTERNAL_DIR = REPO_ROOT / "data" / "external"
RAW_DIR = REPO_ROOT / "data" / "raw"

# -----------------------------------------------------------------------------
# ACTUAL data sources — see docs/data_provenance.md for license details &
# citation instructions for each.
# -----------------------------------------------------------------------------
REAL_DATA_SOURCES = {
    "globsed_sediment_thickness": {
        "url": "https://data.caltech.edu/records/k4070-ngc79",
        "note": "GlobSed (Straume et al., 2019). Caltech archive after NOAA retired the original portal.",
        "format": "NetCDF grid, requires manual download (session/click) then place in data/raw/",
    },
    "global_heat_flow_db_2024": {
        "url": "https://dataservices.gfz-potsdam.de/panmetaworks/showshort.php?id=e6755429-fbbf-11ee-967a-4ffbfe06208e",
        "note": "IHFC Global Heat Flow Database 2024 release, heat-flow data points.",
        "format": "CSV/Excel, download manually from GFZ Potsdam data services",
    },
    "esdm_geomigas": {
        "url": "https://geology.esdm.go.id/geomigas",
        "note": "Map & summary of 128 Indonesian sedimentary basins, Geological Agency of ESDM.",
        "format": "Web app; basin boundaries need manual digitization (QGIS georeferencing) from the displayed maps.",
    },
    "esdm_geomap": {
        "url": "https://geologi.esdm.go.id/geomap",
        "note": "Sedimentary basin maps, Bouguer anomalies, seismotectonic at 1:5,000,000 scale.",
        "format": "Digital map, download & manual georeferencing.",
    },
    "gebco_bathymetry": {
        "url": "https://www.gebco.net/data_and_products/gridded_bathymetry_data/",
        "note": "Global bathymetry, also used in the Malay Basin paper.",
        "format": "NetCDF grid",
    },
    "global_energy_monitor_trackers": {
        "url": "https://globalenergymonitor.org/download-data-success/",
        "note": "Coal Plant Tracker, Cement & Concrete Tracker, Oil & Gas Plant Tracker — CO2 emission sources.",
        "format": "Excel/CSV per tracker, updated periodically (requires filling out a free access form)",
    },
}


def print_real_data_instructions() -> None:
    print("=" * 78)
    print("Open data sources — download manually, then place results in data/raw/")
    print("(full details are in docs/data_provenance.md)")
    print("=" * 78)
    for key, info in REAL_DATA_SOURCES.items():
        print(f"\n[{key}]")
        print(f"  URL   : {info['url']}")
        print(f"  Format: {info['format']}")
        print(f"  Note  : {info['note']}")
    print("\nImportant note: The project development sandbox has limited network access,")
    print("so the download steps above MUST be performed on your own machine")
    print("with full internet access, not via automated scripts here.")
    print("\nAfter downloading the 3 Global Energy Monitor trackers into data/raw/,")
    print("run: python3 src/ingest_raw_data.py")
    print("to convert them into data/raw/indonesia_emitters_real.csv (auto-detected")
    print("by notebooks/00_tier1_national_screening.ipynb).")


def generate_sample_basins(seed: int = 42) -> pd.DataFrame:
    """
    SAMPLE table of ~8 Indonesian basins for Tier-1 screening demo.
    Centroid coordinates are APPROXIMATE (rounded, for map illustration only).
    Capacity columns are intentionally left as placeholders — not real calculation
    results — as the actual capacity workflow only makes sense after the geometry
    of optimal zones (Tier 2) is calculated from actual digitized data.
    """
    data = [
        # name, region, basin_type, tectonic_analogue, lat, lon,
        # is_ccs_policy_priority, exploration_status, srl_placeholder, note
        dict(basin="Sunda-Asri Basin", region="Offshore West Java", basin_type="Rift, saline aquifer + depleted field",
             tectonic_analogue="Malay Basin Analog (Sundaland rift)", lat=-5.6, lon=107.3,
             ccs_policy_priority=True, exploration_status="mature hydrocarbon", srl_placeholder=1,
             note="Official government CCS hub priority (Perpres 14/2024 context); ExxonMobil & Pertamina saline aquifer studies"),
        dict(basin="South Sumatra Basin", region="Onshore/nearshore South Sumatra", basin_type="Foreland/back-arc, depleted field",
             tectonic_analogue="-", lat=-3.3, lon=104.5,
             ccs_policy_priority=True, exploration_status="mature hydrocarbon", srl_placeholder=1,
             note="Sakakemang CCS project (Repsol), target onstream 2027"),
        dict(basin="North Sumatra Basin", region="Onshore/offshore Aceh-North Sumatra", basin_type="Rift/foreland, depleted field",
             tectonic_analogue="-", lat=4.8, lon=97.8,
             ccs_policy_priority=False, exploration_status="mature hydrocarbon (Arun, high-CO2 gas)", srl_placeholder=1,
             note="Historically high-CO2 natural gas (Arun); relevant for source-sink matching"),
        dict(basin="Northwest Java Basin", region="Onshore/offshore West Java", basin_type="Rift, saline aquifer",
             tectonic_analogue="-", lat=-6.0, lon=107.9,
             ccs_policy_priority=False, exploration_status="mature hydrocarbon", srl_placeholder=1,
             note="Close to the Jakarta-Cilegon-Bojonegara industrial cluster"),
        dict(basin="East Java Basin", region="Onshore/offshore East Java", basin_type="Foreland, depleted field",
             tectonic_analogue="-", lat=-7.0, lon=112.5,
             ccs_policy_priority=False, exploration_status="mature hydrocarbon (Gundih)", srl_placeholder=1,
             note="Gundih CCUS project (Pertamina)"),
        dict(basin="Kutai Basin", region="Offshore East Kalimantan", basin_type="Deltaic rift, saline aquifer",
             tectonic_analogue="-", lat=-0.5, lon=117.5,
             ccs_policy_priority=False, exploration_status="mature hydrocarbon", srl_placeholder=1,
             note="Large basin, Mahakam delta, potential not widely studied publicly for CCS"),
        dict(basin="Bintuni Basin", region="Onshore/offshore West Papua", basin_type="Foreland, depleted field",
             tectonic_analogue="-", lat=-2.3, lon=133.5,
             ccs_policy_priority=True, exploration_status="mature hydrocarbon (Tangguh)", srl_placeholder=1,
             note="Official government CCS hub priority; Tangguh CCUS project (BP), frontier data availability"),
        dict(basin="Malay Basin (Natuna, Indonesian side)", region="Offshore Riau Islands", basin_type="Rift, saline aquifer + depleted field",
             tectonic_analogue="Direct Malay Basin analog (same basin system)", lat=3.5, lon=107.0,
             ccs_policy_priority=False, exploration_status="mature hydrocarbon", srl_placeholder=1,
             note="Direct extension of the Malay Basin system — de Jonge-Anderson et al. (2025) methodology is most relevant here"),
    ]
    df = pd.DataFrame(data)
    df["capacity_estimate_status"] = "PLACEHOLDER - not yet calculated from actual digitized data"
    return df


def generate_sample_emitters(seed: int = 42, n: int = 25) -> pd.DataFrame:
    """
    SAMPLE table of CO2 emission sources at industrial scale around Java & Sumatra.
    This is NOT the result of an actual Global Energy Monitor download — just
    random points around publicly known industrial clusters for proximity analysis
    pipeline demo. Replace with actual CSV from GEM after downloading.
    """
    rng = np.random.default_rng(seed)
    clusters = {
        "Jakarta-Cilegon-Bojonegara": (-6.1, 106.3, 8),
        "Surabaya-Gresik": (-7.2, 112.7, 5),
        "Palembang-Muara Enim": (-3.5, 104.2, 4),
        "Medan-Belawan": (3.7, 98.7, 3),
        "Bontang-Balikpapan": (-0.3, 117.4, 3),
        "West Papua (Tangguh)": (-2.3, 133.4, 2),
    }
    rows = []
    sector_choices = ["coal_power", "cement", "oil_gas_processing", "gas_power"]
    for cluster_name, (lat0, lon0, count) in clusters.items():
        for i in range(count):
            rows.append(dict(
                name=f"{cluster_name} - facility {i+1}",
                cluster=cluster_name,
                sector=rng.choice(sector_choices),
                lat=lat0 + rng.normal(0, 0.15),
                lon=lon0 + rng.normal(0, 0.15),
                capacity_mtpa_co2_est=round(float(rng.uniform(0.3, 6.0)), 2),
            ))
    df = pd.DataFrame(rows).head(n)
    df["data_status"] = "SAMPLE/SYNTHETIC - replace with actual Global Energy Monitor tracker"
    return df


def generate_sample_sunda_asri_boundary() -> pd.DataFrame:
    """
    ILLUSTRATIVE polygon boundary for the Sunda-Asri Basin (West Java Sea /
    Sunda Strait area), hand-drawn as a rough placeholder — NOT a digitization
    of an official Badan Geologi map sheet. Used purely so the Tier 2 notebook
    always has a boundary to run against; replace with
    data/processed/sunda_asri_boundary_digitized.csv once QGIS digitization
    from geology.esdm.go.id/geomigas is complete (see docs/data_provenance.md).
    Coordinates order: closed ring (first point repeated at the end).
    """
    vertices = [
        (105.7, -4.3), (106.3, -4.1), (107.0, -4.2), (107.6, -4.5),
        (107.8, -5.0), (107.5, -5.6), (106.8, -5.8), (106.1, -5.6),
        (105.6, -5.1), (105.7, -4.3),
    ]
    return pd.DataFrame(vertices, columns=["lon", "lat"])


def generate_sample_sunda_asri_faults() -> pd.DataFrame:
    """
    ILLUSTRATIVE fault traces within the Sunda-Asri Basin boundary — hand-drawn
    placeholders representing plausible NW-SE / N-S rift-related fault trends
    (consistent with the regional Sundaland extensional setting described in
    [MB] §2), NOT digitized from seismic or official structural maps.
    Each fault has a `fault_id` so multiple line segments can be grouped into
    one fault trace.
    """
    faults = (
        [(105.9, -4.4, 1), (106.4, -4.9, 1), (106.9, -5.4, 1)] +
        [(107.2, -4.4, 2), (107.4, -5.0, 2), (107.1, -5.5, 2)]
    )
    return pd.DataFrame(faults, columns=["lon", "lat", "fault_id"])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=["real", "sample"], default="sample")
    args = parser.parse_args()

    EXTERNAL_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    if args.mode == "real":
        print_real_data_instructions()
        return

    basins = generate_sample_basins()
    emitters = generate_sample_emitters()
    boundary = generate_sample_sunda_asri_boundary()
    faults = generate_sample_sunda_asri_faults()

    basins.to_csv(EXTERNAL_DIR / "sample_basins_indonesia.csv", index=False)
    emitters.to_csv(EXTERNAL_DIR / "sample_emitters_indonesia.csv", index=False)
    boundary.to_csv(EXTERNAL_DIR / "sunda_asri_boundary_illustrative.csv", index=False)
    faults.to_csv(EXTERNAL_DIR / "sunda_asri_faults_illustrative.csv", index=False)

    print(f"Sample data written to:\n"
          f"  {EXTERNAL_DIR / 'sample_basins_indonesia.csv'}\n"
          f"  {EXTERNAL_DIR / 'sample_emitters_indonesia.csv'}\n"
          f"  {EXTERNAL_DIR / 'sunda_asri_boundary_illustrative.csv'}\n"
          f"  {EXTERNAL_DIR / 'sunda_asri_faults_illustrative.csv'}")


if __name__ == "__main__":
    main()